export const metadata = {
  title: "My week",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="w-full h-full  ">
      <div className="overflow-y-auto  h-full ">{children}</div>
    </main>
  );
}
